### PR TITLE
Improve test coverage

### PR DESCRIPTION
**Pull request by uwera**

### CODE REVIEW

**Comment by PEKennedy** [comment]
Finished improving test coverage

**Review by ravenmills3 — APPROVED** [review]
really good work

**Comment by fredy20501** [comment]
Current test coverage: (what is left is the few lines when a database error occurs which we can't replicate easily)
image

**Review by fredy20501 — APPROVED** [review]
I think we're good with what we have (we did reach full coverage as we wanted).

**Pull request merged**
