### PR TITLE
Added export attendance to excel file functionality

### PR DESCRIPTION
**Pull request by fredy20501**

### CODE REVIEW

**Review by JoaoPontes98 — APPROVED** [review]
Looks Good! Just gonna have to make sure these changes will be compatible with the course->section change since the section api is used a lot in this feature

**Comment by fredy20501** [comment]
This is what the excel file looks like:

**Comment by fredy20501** [comment]
image

**Comment by fredy20501** [comment]
@suemelon If you have time can you verify if the format of the excel file matches what Dawn wanted?

**Comment by suemelon** [comment]
> @suemelon If you have time can you verify if the format of the excel file matches what Dawn wanted?

I just sent it along to here to confirm. Will let you know when she verifies.

**Review by ravenmills3 — COMMENTED** [review]
Really not good practice to implement these test changes in this pr. Can you confirm that the code in the test files is the most up to date version and will not affect the QA pr Uwera has put up?

**Comment by fredy20501** [comment]
> Really not good practice to implement these test changes in this pr. Can you confirm that the code in the test files is the most up to date version and will not affect the QA pr Uwera has put up?

There won't be a problem since when both prs will get merged we will resolve the merge conflicts bringing together the best of both prs. In any case if there is an issue we'll see it when the test run automatically and I'll fix it.

**Comment by fredy20501** [comment]
@ravenmills3 
Those fixes are implemented in Uwera's test branch as well (I just happened to notice them when doing this branch a week ago). I have now removed them from this branch.

**Comment by suemelon** [comment]
@fredy20501 Dawn verified the format above is acceptable.

**Review by ravenmills3 — APPROVED** [review]

**Pull request merged**
