### PR TITLE
Added fade transitions and page loading indicators

### PR DESCRIPTION
**Pull request by fredy20501**
- Also modified the dashboard to be actual buttons

### CODE REVIEW

**Comment by fredy20501** [comment]
Here's a GIF showing the new fade transition + loading indicator.
===
Attendance-Tracker-Google-Chrome

**Review by uwera — COMMENTED** [review]
Looks good to me!

**Review by JoaoPontes98 — APPROVED** [review]
Looks good!

**Comment by fredy20501** [comment]
@uwera You left a comment but didn't approve it. Did you mean to approve it, or is there something you want to suggest?

**Review by ravenmills3 — APPROVED** [review]
really good transition and addition to the UX

**Pull request merged**
